version: '3' 
services:
  frontend:
    image: web-data-quality-frontend:3.0.2
    build: ./frontend
    platform: linux/amd64
    container_name: web-data-quality-frontend
    ports:
      - 3000:3000
  back-end:
    image: web-data-quality-backend:3.0.2
    build: ./backend
    platform: linux/amd64
    container_name: web-data-quality-backend
    ports:
      - 8085:8085